services:
  - type: web
    name: restful-checker-api
    runtime: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"